services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret_password
      MYSQL_USER: muzz_db_user
      MYSQL_PASSWORD: muzz_db_password
      MYSQL_DATABASE: muzz_dating_db
    volumes:
      - db_data:/var/lib/mysql # Persist database data
  api:
    build:
      context: .
    environment:
      MYSQL_USER: muzz_db_user
      MYSQL_PASSWORD: muzz_db_password
      MYSQL_DATABASE: muzz_dating_db
    ports:
      - "8888:8888"
    depends_on:
      - db
volumes:
  db_data: # Persist database data volume